# Arquivo que armazena macros de strings de emojis.

CORACAO_VERMELHO = "&#128151;"
ROSTO_SORRIDENTE_COM_OLHOS_SORRIDENTES = "&#x1F60A;"
TEIA_DE_ARANHA = "&#x1F578;"
PRANCHETA = "&#x1F4CB;"
ABOBORA = "&#x1F383;"
CALENDARIO = "&#x1F4C5;"
TACHA = "&#x1F4CC;"
TACHA_REDONDA = "&#x1F4CD;"
TROMPETE = "&#x1F3BA;"
ROSTO_PENSATIVO = "&#x1F914;"
ROSTO_COM_OLHO_PISCANDO = "&#x1F609;"
FOGUETE = "&#x1F680;"
LAMPADA = "&#x1F4A1;"
PERGAMINHO = "&#x1F4DC;"
PILHA_DE_LIVROS = "&#x1F4DA;"
BICEPS = "&#x1F4AA;"
AVISO = "&#x26A0;"
MULHER_LEVANTANDO_A_MAO = "&#x1F64B;"
FANTASMA = "&#x1F47B;"
CONE_DE_FESTA = "&#x1F389;"
ESCREVENDO_A_MAO = "&#x270D;"





"&#;"
"&#x;"